name = "lets-hit-the-gym"
main = "src/index.ts"
compatibility_date = "2024-01-17"

[vars]
TIME_ZONE = "America/Denver"

[triggers]
crons = ["50 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "prod-gym-bot"
database_id = "3ab3c4f1-6812-486e-8e7c-1096b6455733"
migrations_dir = "./migrations"
